### ISSUE TITLE
Seed Choice

### ISSUE THREAD

**Issue by qiwang067** [weipu-zhang/STORM#3]
Hi, Weipu, as described in the STORM paper, "In our experiments, we trained STORM using 5 different seeds.". Could you tell me exactly which five seeds?

**Comment by weipu-zhang** [comment]
Hi,

We used seeds from 1 to 5. But due to CUDA-related hardware problems, we can only guarantee strict replications (exactly same training curves) on the same device.

**Comment by qiwang067** [comment]
> Hi,
> 
> We used seeds from 1 to 5. But due to CUDA-related hardware problems, we can only guarantee strict replications (exactly same training curves) on the same device.

Thank you for your reply!
