### ISSUE TITLE
The result cannot be reproduced

### ISSUE THREAD

**Issue by ZhikanggFu** [weipu-zhang/STORM#6]
The author's work is very good, but why can't we reproduce the results of the paper with our code? For example, the best result of Ms Pacman is 1684.5. It is much worse than the paper.

**Comment by weipu-zhang** [comment]
Hi,

Thanks for the kind words. I've tried two runs today with exactly this codebase, and surely it can reach much higher than 1600. How many seeds have you tested? Also could you share your hardware information and PyTorch version for troubleshooting?

![mspacman](https://github.com/user-attachments/assets/3df1b5f3-81b6-4d9c-942c-5a7669433126)

**Comment by ZhikanggFu** [comment]
Thank you reply, I used two seeds like you. I trained  on the V100 and A100 separately ,but , I got same bad results. My pytorch version is 2.0.1 .
<img width="647" alt="微信图片_20240909140945" src="https://github.com/user-attachments/assets/a9414c8c-45bf-42ee-90dc-90ad670aea79">

**Comment by weipu-zhang** [comment]
Have you run through the 100k steps? From this plot, it seems that you only run about 58*700=40k samples. (The training losses should reach about 100k steps in the Tensorboard logs)

**Comment by ZhikanggFu** [comment]
yeah, I have run through the 100k steps.  The training losses have reach about 100k steps in the Tensorboard logs。The result（1684.5） was got by the eval.sh（ I remove ‘the line ’steps = steps[-1:]' and find the max result）

**Comment by ZhikanggFu** [comment]
> Have you run through the 100k steps? From this plot, it seems that you only run about 58*700=40k samples. (The training losses should reach about 100k steps in the Tensorboard logs)

![Uploading 微信截图_20240909142655.png…]()

**Comment by weipu-zhang** [comment]
Perhaps you may try more seeds on the same device. As plotted in the paper's Appendix A, 1600 still falls in the performance range.

By the way, it's still strange for the episode length and return screenshot you've provided. The sum of the episode lengths should also be near 100k. Could you check the `ckpt` folder and see if the last checkpoint is recorded?

**Comment by ZhikanggFu** [comment]
Thank your advice .My last checkpoint is world_model_100000.pth and agent_100000.pth

**Comment by weipu-zhang** [comment]
I'm closing this issue. If you have any further questions feel free to reopen it.
