### ISSUE TITLE
Discrepancy in MsPacman Results Reproduction: Clarification Needed on SampleMaxSteps

### ISSUE THREAD

**Issue by Dicomsky** [weipu-zhang/STORM#7]
Hi, thank you for the great work!

While reproducing the MsPacman results, I noticed that my performance is significantly lower than what's reported in the paper. I want to clarify if the x-axis in Figure 3(b) and Figure A represents 400k SampleMaxSteps. Does it mean all results in the paper are based on 400k SampleMaxSteps?

If so, my 100k SampleMaxSteps result would naturally represent only 1/4 of the time. Please confirm if my understanding is correct.

Thanks a lot!

Configuration:

SampleMaxSteps: 102000
BufferMaxLength: 100000
BufferWarmUp: 1024
![1728245087694](https://github.com/user-attachments/assets/66c65eac-09b1-440e-8651-1bfceaf2a113)
![image](https://github.com/user-attachments/assets/0c84225c-3dde-4b4b-a28a-d9f7fa4854fe)

**Comment by weipu-zhang** [comment]
Hi,

The max step is 100k. Atari 100k benchmark use a frameskip of 4, and the 400k in the plots corresponds to the original sample steps in the ALE environment. (So a 400k run would correspond to a 1600k plot.)

As for the performance on MsPacman, you may refer to other issues in this repo. If you've runned more than 5 seeds and still find the result inconsistent, you can post your tensorboard screenshot here for further discussion.

**Comment by Dicomsky** [comment]
Thank you for your response!
I test several random seeds and got almost the same results with the papers. 
Thank you again. And I think you could close this issue.
